### ISSUE TITLE
enablePrebidCache should default to true

### ISSUE THREAD

**Issue by graphicdeveloper** [prebid/prebid-js-plugin-brightcove#12]
The plugin does not currently default to enablePrebidCache = true. It also doesn't currently use a default prebid cache url, if none is set by the publisher. Both of these defaults should be set to ensure prebid caching works by default.

**Comment by vpitts** [comment]
This issue has been fixed in version 0.2.  The default value for enablePrebidCache is now true.  So unless the publisher wants to disable prebid cache, they do NOT need to specify this argument in the prebid options. 

In addition, if the publishers are using the default prebid url, they do NOT need to specify a prebid cache url.  The only time they need to specify a default value is if they are using a custom url for prebid cache.
